### ISSUE TITLE
Can't use metablock as voting item

### ISSUE THREAD

**Issue by xion87** [stefvanschie/buildinggame#10]
I would like to use metablock like coloured clay or coloured wool, i tried to use this without success, (it say wrong id)
voting:
  default-vote-points: 5
  second-slot:
    id: coal_block
    points: 0
  third-slot:
    id: '159:6'
    points: 1
  fourth-slot:
    id: '159:14'
    points: 2
  fifth-slot:
    id: '159:4'
    points: 3
  sixth-slot:
    id: '159:5'
    points: 4
  seventh-slot:
    id: '159:3'
    points: 5
  eighth-slot:
    id: '159:10'
    points: 6

**Comment by stefvanschie** [comment]
Use alphabetical ids instead of numerical ids (stained_hardened_clay:6)

**Comment by xion87** [comment]
was stained_clay :P , it worked fine :) thank you!
