### ISSUE TITLE
Its off

### ISSUE THREAD

**Issue by draebersnegl** [stefvanschie/buildinggame#105]
https://github.com/stefvanschie/buildinggame/blob/537c85e01e7967d059d07146be267beee422494c/buildinggame/src/main/java/com/gmail/stefvanschiedev/buildinggame/utils/bungeecord/BungeeCordHandler.java#L7
Should be "_import fr.rhaz.socketapi.Bukkit;_" according to fr.rhaz.socketapi.1.6.3

https://github.com/stefvanschie/buildinggame/blob/537c85e01e7967d059d07146be267beee422494c/buildinggame/src/main/java/com/gmail/stefvanschiedev/buildinggame/utils/bungeecord/BungeeCordHandler.java#L8
Should be "_import fr.rhaz.socketapi.SocketAPI;_" according to fr.rhaz.socketapi.1.6.3

https://github.com/stefvanschie/buildinggame/blob/537c85e01e7967d059d07146be267beee422494c/buildinggame/src/main/java/com/gmail/stefvanschiedev/buildinggame/utils/bungeecord/BungeeCordHandler.java#L60
Socket4MC.bukkit() most be _SocketAPI.bukkit()_

**Comment by stefvanschie** [comment]
Socket4MC should be updated in its entirety to version 2.1.7, planned for 5.5.2 release.

**Comment by stefvanschie** [comment]
Has been addressed in the latest commit.
