### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by xion87** [stefvanschie/buildinggame#11]
1) I would like to see an option for toggle who voted you message and the scoreboard, so that it feel more like the hypixel one
2) Separate the chat between arena and the user that are playing on tab (if possible)
3) banners like buildbattle
Thank you a lot again :)

**Comment by stefvanschie** [comment]
1) I'll add it in the next update.
2) I'll do the chat in the next update and I'll see if I can make the tab too.
3) Vote on that here: http://dev.bukkit.org/bukkit-plugins/buildinggame/polls/what-should-i-make-first/

**Comment by stefvanschie** [comment]
Added 1) and 2) in version 2.2.1
