### ISSUE TITLE
Suggestion on enhance config for database settings

### ISSUE THREAD

**Issue by draebersnegl** [stefvanschie/buildinggame#117]
Would it be possible to add something like stats.database.extra.xxx to config?
i.e. stats.database.extra.useSSL: true|false

and do a loop for extras in com.gmail.stefvanschiedev.buildinggame.managers.stats.ConnectionManager.configureConnPool()

**Comment by stefvanschie** [comment]
I can add some more options for enhanced configuration of the database settings in the next update.

**Comment by stefvanschie** [comment]
Note that I cannot enable/disable SSL as you've showed in the example. The database manager (HikariCP) doesn't know what SSL is and therefore I can't enable/disable it.

**Comment by stefvanschie** [comment]
Has been addressed in the latest commit.
