### ISSUE TITLE
the file signs keep to random reset at each server restart

### ISSUE THREAD

**Issue by Malachiel87** [stefvanschie/buildinggame#119]
*You can discard this template if you're submitting a code fix/spelling mistake etc.* __Don't__ *discard this when you're submitting a bug*

## Issue

__I'm using version:__  5.5.5
__I'm on Minecraft:__ 1.12.2
__I'm running:__ Paperspigot

__Seen results:__  
The file signs.yml keep to randomly reseting at each server restart. If i setup all signs these are working correct until 1-3 server restart and i see the file signs become empy again after these restart

**Comment by stefvanschie** [comment]
Closing this, since the version is no longer supported and inactivity. If this still occurs on a recent version, please comment.
