### ISSUE TITLE
Buildiinggame party mode vote phase

### ISSUE THREAD

**Issue by xion87** [stefvanschie/buildinggame#13]
When a vote phase start on builiding game party, it teleport all members for a fraction of a second into a random plot and then it teleport on right plot and start vote phase, is normal? (no errors)

**Comment by stefvanschie** [comment]
Doesn't seem to happen for me. Does this only happen with team mode or also solo mode?

**Comment by xion87** [comment]
team mode

**Comment by xion87** [comment]
More information the issue happen only with 3+ parties (with 2 parties is fine)
