### ISSUE TITLE
BuildingGame making BukkitScheduler use 100% (or close to) CPU

### ISSUE THREAD

**Issue by dordsor21** [stefvanschie/buildinggame#146]
## High (100%) thread CPU usage when BuildingGame is enabled - BukkitScheduler

__I'm using version:__ *5.8.3*  
__I'm on Minecraft:__ *1.12.2*  
__I'm running:__ *PaperSpigot*

__How to reproduce:__  
Have it installed it seems. I also have not set anything up, (no arenas/plots etc)

__Additional info:__  
![image](https://user-images.githubusercontent.com/10080017/40977000-a5565f44-68c7-11e8-8932-de49fb584925.png)

![image](https://user-images.githubusercontent.com/10080017/40977004-a87c2960-68c7-11e8-845e-f5169b1e614a.png)

**Comment by dordsor21** [comment]
It was update 5.7.0 that caused the issue

**Comment by stefvanschie** [comment]
Do you have a link to a timings report in which this behavior is visible?

**Comment by dordsor21** [comment]
https://timings.aikar.co/?id=3796806547734635b2b4f8a38d6eaa7f#plugins

**Comment by stefvanschie** [comment]
Should be fixed in the 5.8.4 release.

**Comment by dordsor21** [comment]
Fantastic, thanks!
