### ISSUE TITLE
Vote spam

### ISSUE THREAD

**Issue by xion87** [stefvanschie/buildinggame#15]
I noticed people can vote spam and i receive like 10 message per second, is pretty anoying, i suggest to add a cooldown, ortherwhite there is a way for dont receive these messages and make them anoymous/hide vote scoreboard and show it only to end?

**Comment by stefvanschie** [comment]
You can set the amount of times people can change their vote in the config.yml.

**Comment by xion87** [comment]
And for disable the message is possible?

**Comment by stefvanschie** [comment]
Empty message doesn't display anything.

**Comment by xion87** [comment]
No more a issue, i am closing it since i disabled messages :)
