### ISSUE TITLE
Water and Leaf go outside the plots

### ISSUE THREAD

**Issue by xion87** [stefvanschie/buildinggame#17]
Tree Leafs go outside the plot: http://i.imgur.com/zOwuO1h.jpg

Water/freezed lava go outside of top plot: http://i.imgur.com/1G9hzVD.jpg

I am using now the plugin in a dedicated server as multiarena so i will report all issue that i will find ^^, thank you for your amazing work!

**Comment by stefvanschie** [comment]
Are you using version 2.1.1 or higher? It should be fixed in those versions.

**Comment by xion87** [comment]
i am using 2.2.5 Buildiing version, i have opened the server to pubblic with 2.2.4 version

**Comment by xion87** [comment]
i confirm the issue persist, i got all arena with water/lava upside and broken border on external arena (caused by lava falling)

**Comment by stefvanschie** [comment]
I found the issue for the water and lava, but not for the leaves though. Is it a specific type of leave each time or are it all sorts of leaves?

**Comment by xion87** [comment]
dark oak leaves, jungle leaves, also there are cobblestone generated by lava and water

**Comment by stefvanschie** [comment]
I see apparently trees growing naturally can go outside the plot. I'll see if I can fix this.

**Comment by stefvanschie** [comment]
Found the issue and will be fixed in the next version.

**Comment by xion87** [comment]
great, hopeful also the lava/water/cobblestone issue is fixed, my maps are all griefed xD

**Comment by stefvanschie** [comment]
Issue fixed in version 2.2.7
