### ISSUE TITLE
Voting,Fireworks and auto-leave?

### ISSUE THREAD

**Issue by LilaParadiseRealms** [stefvanschie/buildinggame#180]
*You can discard this template if you're submitting a code fix/spelling mistake etc.* __Don't__ *discard this when you're submitting a bug*

## Issue

__I'm using version:__ 6.1.0 
__I'm on Minecraft:__ 1.13.1
__I'm running:__ Spigot

__Seen results:__  
I followed instructions on the wiki to set up a lobby and solo arena. Works perfectly until it is time for voting. Players are teleported to the plot and it states who's plot it is, but when trying to vote it says "You can't vote on your own plot" for every plot, causing the default points to be given. Then it teleports all of us to the winning plot (how does it pick a plot if everyone got 5 points?) and there are no fireworks for winner. I'm not sure if it is suppose to after the game, but it doesn't auto teleport back to main lobby, we are stuck just sitting in winning plot until we type /bg leave. I am not sure if that is how it is suppose to be. If so, I'd like to suggest an auto leave.

__Expected results:__  
Expect each plot to get votes from everyone (besides the plot owner of course) and fireworks for the winner

__How to reproduce:__  
I set it up with no problem, just running the plugin normal and all good until voting/end of game.

__Additional info:__  
(https://pastebin.com/J0nK4fje) this shows what was happening in console during voting. I don't know if this is an issue with another plugin on our server or what...sorry I don't know much but I thought it would be worth a try to ask for help :) Thank you!

**Comment by stefvanschie** [comment]
Which version of WorldEdit do you have installed?

**Comment by LilaParadiseRealms** [comment]
I just realized that I'm a few builds behind from current World Edit, server has build #3869. I'm going to try and update it and I'll come back and let you know if anything changed!

**Comment by LilaParadiseRealms** [comment]
I have put build #3888 of world edit. Still doing the same thing.

**Comment by stefvanschie** [comment]
Thanks, this should hopefully be fixed in the next version.

**Comment by stefvanschie** [comment]
This has been fixed in the latest commit.
