### ISSUE TITLE
 Inventoryclick error

### ISSUE THREAD

**Issue by xion87** [stefvanschie/buildinggame#19]
Randomly i got this error on console, no other errors (4-5 times for day)
http://hastebin.com/getabakara.avrasm

**Comment by stefvanschie** [comment]
Could you show your config please?

**Comment by xion87** [comment]
there is my config
http://hastebin.com/zufotenomu.sm

**Comment by stefvanschie** [comment]
Will be fixed in the next version.

**Comment by stefvanschie** [comment]
Fixed in version 2.2.6
