### ISSUE TITLE
error

### ISSUE THREAD

**Issue by anemul** [stefvanschie/buildinggame#192]
*You can discard this template if you're submitting a code fix/spelling mistake etc.* __Don't__ *discard this when you're submitting a bug*

## Issue

__I'm using version:__ *6.5.0*  
__I'm on Minecraft:__ *1.13.2*  
__I'm running:__ *Bukkit/Spigot*

__Seen results:__  
installed plugin and recieved the following error : https://pastebin.com/VJqcfM9K

__Expected results:__  
*it should have loaded :(*

__How to reproduce:__  
*for me it is just trying load it .*

__Additional info:__  
*more info you'd like to give us*

**Comment by stefvanschie** [comment]
Like I also mentioned on the Spigot page, the plugin requires Java 11 to work.
