### ISSUE TITLE
Scoreboard is flickering

### ISSUE THREAD

**Issue by Promic2** [stefvanschie/buildinggame#2]
Scoreboard is flickering when updating to players 

edit

**Comment by stefvanschie** [comment]
What do you exactly mean with global chat. The chat can only be seen by people in the game.

**Comment by Promic2** [comment]
it was just when I was in the arena,
I could see the lobby chat it was my own fault not yours 
i just fix it with the essentials chat radius command :-)

**Comment by stefvanschie** [comment]
Ok
