### ISSUE TITLE
Massive error spam and high ram usage

### ISSUE THREAD

**Issue by xion87** [stefvanschie/buildinggame#20]
I noticed buildiinggame is using a ton of ram almost 6 mb (5-15 player 5 arenas in dedicated server) in half day and i got the console spammed by these errors http://hastebin.com/kalucopomu.avrasm
and http://hastebin.com/kovekaxali.avrasm

**Comment by stefvanschie** [comment]
For the errors have you set the boundaries for all plots (including ones which are not in use)?

**Comment by xion87** [comment]
mm i just added some unfinished arena, i will remove them for see if errors go

**Comment by xion87** [comment]
erros gone, i removed the incomplete arenas from config

**Comment by stefvanschie** [comment]
That's good to know

**Comment by xion87** [comment]
i think is all resolved :)
