### ISSUE TITLE
Error when using /bg setspawn

### ISSUE THREAD

**Issue by CommanderBeaver** [stefvanschie/buildinggame#200]
## Issue

__I'm using version:__ 7.0.0
__I'm on Minecraft:__ 1.14.4 
__I'm running:__ Spigot (paper)

__Seen results:__  
error occurs when using /bg setspawn

__Expected results:__  
set a spawn

__How to reproduce:__  
use /bg setspawn when making an arena in 1.14.4
[Error report in CMD.txt](https://github.com/stefvanschie/buildinggame/files/3437803/Error.report.in.CMD.txt)

**Comment by GoldenEdit** [comment]
The same thing happened to me.
**I'm using version:** 7.0.0
**I'm on Minecraft:** 1.14.4
**I'm running:** Spigot (paper)
Could I know how long until a fix?

**Comment by stefvanschie** [comment]
I'm currently on vacation and I'll be back on August 9. So, I'll probably start working on this August 10 and I think I should be able to get this fixed that weekend. Of course, anyone else is free to make a PR fixing this if they want to, but even then, releasing the new version will have to wait until I get back.

**Comment by stefvanschie** [comment]
This has been addressed in the commit [9de7bad](https://github.com/stefvanschie/buildinggame/commit/9de7badd351165f223d24b079efe6a66f882e60f).
