### ISSUE TITLE
stats not saved anymore?

### ISSUE THREAD

**Issue by xion87** [stefvanschie/buildinggame#21]
i just opened stats.yml and there was only this... is normal?
019b3f01-9c76-3d3d-909c-d1d6b9e9576f:
  walked: 406
  plays: 1
963af6b9-bd01-31a4-a004-3b8e66b35bd4:
  walked: 20
1bb7cd84-1d54-3b54-a2a8-6b3d5ac11bb7:
  walked: 150

**Comment by stefvanschie** [comment]
It only saves the stats which have values. So it's normal that you don't see every statistic for each player. Are these ones the only players there are in the files? Or is this just a part of the file?

**Comment by xion87** [comment]
is all data that is saved in stats, after 1 week of buildbattle play

**Comment by stefvanschie** [comment]
Can everybody still see their stats or are they gone?

**Comment by xion87** [comment]
stats are gone

**Comment by xion87** [comment]
mmm i noticed now was added only this 
953064a4-275d-3097-bd3a-87fdc547bbdf:
  walked: 2
there is a permission for have the stats registred? because i think only opped player got stats

**Comment by xion87** [comment]
I confirm stats are broken, was working in a older version. is not saving any user

**Comment by stefvanschie** [comment]
Well in 2.2.1 it would only save stats for people online and bug when people in stats were offline. The only thing I can think off is it only saving offline players, but the amount of stats saved is way too little to be for only offline players. I also checked it and it will get both online and offline players.

**Comment by xion87** [comment]
is because maybe i am using offline mode?

**Comment by stefvanschie** [comment]
That shouldn't matter. Offline mode only stops checking if the user has bought the game.

**Comment by xion87** [comment]
so why is not working for me?

**Comment by stefvanschie** [comment]
Sadly, I have no idea.

**Comment by xion87** [comment]
maybe is because i have the server under bungee?

**Comment by stefvanschie** [comment]
Bungeecord doesn't affect the normal spigot servers. It only gets information from them.

**Comment by stefvanschie** [comment]
It could be that the plugin was trying to save data when the server crashed, so it couldn't finish adding the stats in the files. That's the only thing I can think of.

**Comment by stefvanschie** [comment]
I haven't confirmed it, but it could be that it was fixed in the latest version (fixed an error with saving stats). I suggest trying the latest version and see if the stats get saved correctly.

**Comment by xion87** [comment]
stats file is still empy :c also with latest release

**Comment by stefvanschie** [comment]
In your config.yml is _stat.enable_ set to true?

**Comment by xion87** [comment]
yeah all enabled
