### ISSUE TITLE
Time statistic not working

### ISSUE THREAD

**Issue by danil20028191** [stefvanschie/buildinggame#217]
*You can discard this template if you're submitting a code fix/spelling mistake etc.* __Don't__ *discard this when you're submitting a bug*

## Issue

__I'm using version:__ *insert version*  
__I'm on Minecraft:__ *insert version*  
__I'm running:__ *Bukkit/Spigot*

__Seen results:__  
*tell use what happened*

__Expected results:__  
*tell use what should have happened*

__How to reproduce:__  
*tell how this bug occured, so we can try it out ourselves*

__Additional info:__  
*more info you'd like to give us*

**Comment by danil20028191** [comment]
Time statistic not working not counts time played:

# -----------------------------------------
# 
#            Statistic config
# 
#            Name: %statistic_time_played%
# 
# -----------------------------------------
# 
#     Explanation of options:
# 
#     statistic-name: the name of the statistic. If you change this, signs will no longer be linked to 
#        this statistic. The statistic-name is mainly used for the database.
# 
#     placeholder: the actual placeholder being used. By default this will be the same as
#        statistic-name, but you can change this to something different without changing the statistic-name
# 
#     order-mode: how this statistic will be ordered in the leaderboard. Options: descending, ascending
# 
#     update-interval: the time in seconds between updates of this statistic
# 
#     force-update: whether the plugin should update the data
#        of this statistic in the background even if no sign is made for its leaderboard
# 
#     enable-commas: whether to add commas to the format of the statistic (e.g. 9,000,000)
# 
#     statistic-type: The type of the statistic is used when formatting its value in signs, menus, holograms etc.
#        money: if your statistic represents a very large monetary amount, such as 5 quadrillion, this will format 
#            your very large numbers properly, using the money-format configured in the config.yml
#        time-seconds: if your statistic represents a time in seconds his will format your time properly 
#            and split it into days, hours, minutes and seconds using the time-format configured in the config.yml
#        time-milliseconds: similar to the other time options, this type is used for statistic that represent a time in milliseconds
#        time-minutes: similar to the other time options, this type is used for statistic that represent a time in minutes
#        time-hours: similar to the other time options, this type is used for statistic that represent a time in hours
# 
#     sign-lines: the lines on the sign of the leaderboard. Variables: {rank}, {name}, {value}
# 
#     menu-lines: the lines on the skulls in the menu of the leaderboard. Variables: {rank}, {name}, {value}
# 
#     menu-enabled: whether the menu for checking the leaderboard players should be enabled
# 
#     menu-title: the title of the menu for checking the leaderboard players. Variables: {page}
# 
#     menu-command: the command used for opening the menu for checking the leaderboard players
# 
#     menu-size: the size of the menu for checking the leaderboard players. If you set this higher 
#        than 54, multiple pages will be created 
# 
#     citizens-nametag: the nametag that will be used when creating a Citizens NPC linked to a sign.
#        Variables: {rank}, {name}, {value}
# 
#     armorstand-nametag: the nametag that will be used when creating an armorstand linked to a sign.
#        Set this to an empty string to disable this feature
#        Variables: {rank}, {name}, {value}
# 
# -----------------------------------------

statistic-name: '%statistic_time_played%'
placeholder: '%statistic_time_played%'
order-mode: descending
update-interval: 30
statistic-type: time
force-update: true
enable-commas: true
alltime:
  sign-lines:
  - '§8§m---------§8[ §c{rank} §8]§8§m---------'
  - ' &eName:&a {name}'
  - ' &eValue:&f {value}'
  - '§8§m----------------------'
  menu-lines:
  - '§8§m---------§8[ §c{rank} §8]§8§m---------'
  - ' &Name:&a {name}'
  - ' &eValue:&f {value}'
  - '§8§m----------------------'
  menu-enabled: true
  menu-title: '           §0⌛ Top Time ⌛'
  menu-command: /toptime
  menu-size: 90
  citizens-nametag: '&6&l#{rank} &b{name} &f- &b{value}'
  armorstand-nametag: '&6&l#{rank} &b{name} &f- &b{value}'

**Comment by stefvanschie** [comment]
The placeholder you mentioned isn't from this plugin, nor is the config you showed. Did you perhaps create this issue on the wrong repository?
