### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by xion87** [stefvanschie/buildinggame#22]
yesterday my buildiingame server crashed with this log
http://hastebin.com/ukalakoheq.avrasm
Bulidingame 2.2.6
Spigot 1.8.8

**Comment by stefvanschie** [comment]
Hmm, I tried to do the same as a user on your server did, but it didn't end up with this log. Did my plugin cause much lag / overload on your server? Because that's most likely why it has crashed.

**Comment by xion87** [comment]
maybe i think is related to the server crash of my network in that day, but i will investigate

**Comment by xion87** [comment]
yesterday again another crash http://hastebin.com/wanonipova.avrasm

**Comment by stefvanschie** [comment]
I'm not sure if this is due to this plugin. The plugin only tries to stop the arena, because of people leaving due to the server crash. I think it's best to report this on spigotmc.org and see what the people on there think of it. They probably have more experience with server crashes than I have.
