### ISSUE TITLE
Inventoryclick error (ye again)

### ISSUE THREAD

**Issue by xion87** [stefvanschie/buildinggame#23]
sadly i got 2 times the error today:
http://hastebin.com/ovucoqagok.avrasm

**Comment by stefvanschie** [comment]
Could I see your config.yml?

**Comment by xion87** [comment]
http://hastebin.com/oxuwukenub.sm

**Comment by stefvanschie** [comment]
How many teams do you have (maximum)?

**Comment by xion87** [comment]
on team mode? max player is 14, 7 plots, min player 4 for start

**Comment by stefvanschie** [comment]
Could I see your arenas.yml?

**Comment by xion87** [comment]
sure http://hastebin.com/emuhequrag.sm

**Comment by stefvanschie** [comment]
Thank you, I think I found the issue, so it will hopefully be solved in the next version.

**Comment by stefvanschie** [comment]
Fixed in version 2.3.0.
