### ISSUE TITLE
Players can't place items in item frames.

### ISSUE THREAD

**Issue by zedwick** [stefvanschie/buildinggame#235]
Players can't place items in item frames, as it instead comes up with a mob options menu.

## Issue

__I'm using version:__ 9.0.3  
__I'm on Minecraft:__ 1.16.3
__I'm running:__ Paper

__Seen results:__  
Right clicking an item frame with an item in hand will open the mob options menu, with a single option: remove

__Expected results:__  
I expected the item in my hand to be placed into the item frame.

__How to reproduce:__  

1. Place an item frame during the build phase
2. Hold an item in your hand
3. Right click the item frame
4, <item frame remains empty, options menu opens>

__Additional info:__  
I'm not sure how you would maintain the options menu whilst also allowing items to be placed in item frames. Perhaps shift+right-click to open the menu? Or only open it with an empty hand?

Worth mentioning a similar issue exists for boats. Can't sit in your boat to move it around, as right-clicking the boat opens the options menu. Probably a bit more of a niche use-case than items in item frames, though.

**Comment by stefvanschie** [comment]
Thank you, this will be fixed in version 9.1.0. I've used your suggestion of only opening the menu when holding shift for boats, item frames and minecarts.
