### ISSUE TITLE
Players are able to remove entities from other players' plots.

### ISSUE THREAD

**Issue by zedwick** [stefvanschie/buildinggame#236]
Players are able to remove other players' entities by right clicking an entity during the vote phase to open the mob options menu to remove it.

## Issue

__I'm using version:__ 9.0.3
__I'm on Minecraft:__ 1.16.3
__I'm running:__ Paper

__Seen results:__  
Right clicking an entity (item frame) in another players' plot during the voting phase opens the mob options menu, which allows removing the entity despite it being in another player's plot (and not being in the build phase)

__Expected results:__  
Players should not be able to remove/modify entities in other players' plots.
Players should not be able to remove/modify entities from any plot, even their own, outside of the build phase.

__How to reproduce:__  

1. During the Build phase: Player A places an item frame in their plot
2. During the voting phase: Player B, whilst viewing Player A's plot, right-clicks the item frame and clicks remove in the menu.

**Comment by stefvanschie** [comment]
Thank you for the report, this will be fixed in 9.1.0.
