### ISSUE TITLE
[Suggestion] Add a config option to disable the mob options menu entirely.

### ISSUE THREAD

**Issue by zedwick** [stefvanschie/buildinggame#237]
I have the mob menu and spawning mobs disabled, so of the two entities which will open the mob options menu when right-clicked (item frames and boats), neither have any options in the menu beyond removing the entity. Item frames can be removed by hand, though I think boats might not be able to be removed by hand.

I would like to disable the mob options menu mainly due to the other issues I've opened (#235 & #236) but also as it is not used on my server.

**Comment by stefvanschie** [comment]
Thank you, this will be added in 9.1.0.
