### ISSUE TITLE
[Suggestion] Add a config option to allow pistons in plots.

### ISSUE THREAD

**Issue by zedwick** [stefvanschie/buildinggame#238]
Though I wouldn't like pistons to be able to move blocks outside of a plot, I would still like players to be able to create interesting moving build elements using pistons.

**Comment by stefvanschie** [comment]
Thank you. Pistons will now behave as expected: pushing and pulling within a plot works like normal, but they won't work if you try to push blocks outside your plot or pull blocks from outside your plot to the inside. An accompanying option has been added to either enable the behavior as described or disable them entirely (pushing and pulling doesn't work at all).
