### ISSUE TITLE
Tnt make walls outside plot to explode

### ISSUE THREAD

**Issue by xion87** [stefvanschie/buildinggame#24]
http://i.imgur.com/ykyaRoy.jpg
 i dont have any clue what is happened... i am using latest release

**Comment by xion87** [comment]
Tnt that going outside plot they destroy all walls, i tested it by making a tnt tower, and turn it on

**Comment by stefvanschie** [comment]
I see, I'll try to find a solution. For now you can add tnt to the blocked blocks list, so this doesn't occur.

**Comment by stefvanschie** [comment]
Found a solution, this will be fixed in the next update

**Comment by xion87** [comment]
thank you :)

**Comment by xion87** [comment]
also i noticed the mobs outside plots are not removed

**Comment by stefvanschie** [comment]
Nothing is done outside plots, mobs have no ai by default, so they can't walk out of the plot.

**Comment by xion87** [comment]
so why i see mob spawnend outside the buildiing zone?  also they pretty much like 100-300 mobs for each arena, i think something is spawning them

**Comment by stefvanschie** [comment]
One thing that could be spawning them are spawners. However unless you have the 'give' command whitelisted in your config.yml, you can't get a mob spawner.

**Comment by xion87** [comment]
is not mob spawner....  i tried to use eggs and i was able to spam the mobs outside plots without issues o.o (was op into game)

**Comment by stefvanschie** [comment]
That's something I didn't think of. I will fix it in the next version.

**Comment by stefvanschie** [comment]
Solved in verison 3.0.0 (the mobs and the tnt)
