### ISSUE TITLE
Antiflickr method for scoreboard

### ISSUE THREAD

**Issue by xion87** [stefvanschie/buildinggame#25]
Hi i noticed that scoreboard flickr a lot, and i got a friend dev that is using a perfect scoreboard (counterstrike author). he tell me some tips that you can use for it
 If you want to do a scoreboard update without lag use this:
 - Makes a scoreboard using teams, but the players name must be colors,
 - you should keep the team members saved for easy acces
 - then update prefix and suffixes only and for suffixes get the last color from prefix

**Comment by stefvanschie** [comment]
I've seen this method a few times, however I've never used it, I'll experiment with it and see if I can implement it with the current way scoreboards are handled.

**Comment by stefvanschie** [comment]
Added in version 3.0.0
