### ISSUE TITLE
Voting using item not working as intended

### ISSUE THREAD

**Issue by Kolgrath** [stefvanschie/buildinggame#280]
*You can discard this template if you're submitting a code fix/spelling mistake etc.* __Don't__ *discard this when you're submitting a bug*

## Issue

__I'm using version:__ 9.1.2  
__I'm on Minecraft:__ 1.16.5  
__I'm running:__ Spigot 3015-Spigot-73fb609-b7eed25 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) (Latest Version)

__Seen results:__  
During the vote phase left clicking or right clicking any of the default voting items (coal block, emerald block, etc) does not produce a vote. There are no errors or commands issued in console when clicking.

__Expected results:__  
When clicking a vote block points should be awarded to the builder based on which item is being clicked with to vote

__How to reproduce:__  
Created 1 arena on a new install of Spigot
Using these plugins:
LuckPerms, Spawntp, Vault, PlaceholderAPI, WorldEdit, Essentials, GHolo, EssentialsSpawn, WorldGuard, BuildingGame, ChatControl

__Additional info:__  
N/A

**Comment by stefvanschie** [comment]
Thank you, this will be fixed in the next version.
