### ISSUE TITLE
Vote period not equal for all plots

### ISSUE THREAD

**Issue by zedwick** [stefvanschie/buildinggame#29]
Sometimes the time players have to vote for a winner is not as configured. In my case the voting for plot 1 can last a very short period of time, 10 or so seconds, where-as others last the full 70 seconds as configured.

I haven't been able to work out a direct pattern, as this happens after the initial round following server start and in later games, but may not always occur.

BuildingGame 3.1.2 on Paper-805

**Comment by stefvanschie** [comment]
Could you please show your config.yml as well as your arenas.yml?

**Comment by zedwick** [comment]
Looking at the configs, I can see why it might be selecting two different lengths of time, as the arena.yml has a vote timer option- just not sure why it's using the value from config.yml most of the time, and sometimes using the value from arena.yml.

config.yml:
`timer: 300
votetimer: 70
waittimer: 50
wintimer: 60
loading:
  load-after-plugins: true
allow-fly-out-bounds: true
enable-subject-voting: false
restore-plots: true
scoreboard-update-delay: 20
max-vote-change: -1
max-particles: 5
names-after-voting: false
enable-item-drop: false
stats:
  save-delay: 900
subjects:
- dog
- house
- toilet
- superman
- superhero
- car
- book
- candy
- flower
- headset
blocked-entities:
- ender_crystal
- ender_dragon
- wither
blocks:
  blocked:
  - command
  - command_minecart
bossbar:
  color: purple
  style: solid
mobs:
  enable-noai: true
  allow: true
title:
  fade_in: 0
  stay: 0
  fade_out: 0
  syncronize: false
voting:
  default-vote-points: 5
  second-slot:
    id: coal_block
    points: 2
  third-slot:
    id: iron_block
    points: 3
  fourth-slot:
    id: lapis_block
    points: 4
  fifth-slot:
    id: redstone_block
    points: 5
  sixth-slot:
    id: gold_block
    points: 6
  seventh-slot:
    id: diamond_block
    points: 7
  eighth-slot:
    id: emerald_block
    points: 8
plots:
  floor:
    allow-air: false
command-whitelist:
- give
- gamemode
win-commands: []
#- execute %winner% ~1 ~ ~-4 summon FireworksRocketEntity ~ ~5 ~ {FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:0,Colors:[14263784,581228,995542,3255052,13888116,4175055],FadeColors:[8848460]}]}}}}
#- execute %winner% ~-2 ~ ~3 summon FireworksRocketEntity ~ ~5 ~ {FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:2,Colors:[14495340,12909992,8969028,7924605],FadeColors:[10438567,12267580,2724499,9942861]}]}}}}
#- execute %winner% ~-4 ~ ~1 summon FireworksRocketEntity ~ ~5 ~ {FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:0,Colors:[2540754],FadeColors:[14655338,2417053,631931,4555299,15572482,3482736,693669]}]}}}}
money:
  first: 20
  second: 10
  third: 5
  others: 0
commands:
  first:
  - null
  second:
  - null
  third:
  - null
  others:
  - null
leave-item:
  slot: 8
  id: watch
subject-gui:
  item:
    id: paper
bungeecord:
  enable: true
team-selection:
  show-names-as-lore: false
  item:
    id: paper
  team:
    '1':
      id: paper
    '2':
      id: paper
    '3':
      id: paper
    '4':
      id: paper
    '5':
      id: paper
    '6':
      id: paper
    '7':
      id: paper
    '8':
      id: paper
    '9':
      id: paper
    '10':
      id: paper
gui:
  particles:
    id: red_rose
    enabled: true
  floor:
    id: hard_clay
    enabled: false
  time:
    id: watch
    enabled: false
  rain:
    id: water_bucket
    enabled: false
  fly-speed:
    id: feather
    enabled: false
  heads:
    id: skull_item:3
    enabled: true
debug: false
clean-files: false
timings:
  lobby-timer:
    at:
      '0':
      - tellraw @a ["",{"text":"The %arena% has started!","color":"aqua"},{"text":" Slap the spectate sign to watch!","color":"dark_aqua"}]
      '10':
      - tellraw @a ["",{"text":"The %arena% will start in 10 seconds!","color":"aqua"},{"text":" Use the sign to join!","color":"dark_aqua"}]
      '45':
      - tellraw @a ["",{"text":"The next %arena% will start in 45 seconds!","color":"aqua"},{"text":" Use the sign to join!","color":"dark_aqua"}]
  build-timer: {}
  vote-timer: {}
  win-timer: {}
`

arena.yml:
`main-spawn:
  server: Zedwick
  world: BuildOff
  x: 118
  y: 37
  z: 561
PocketBuildOff:
  mode: SOLO
  timer: 300
  lobby-timer: 60
  vote-timer: 15
  win-timer: 10
  '1':
    server: Zedwick
    world: BuildOff
    x: 274
    y: 1
    z: 474
    high:
      world: BuildOff
      x: 281
      y: 31
      z: 468
    low:
      world: BuildOff
      x: 266
      y: 1
      z: 449
    floor:
      high:
        world: BuildOff
        x: 281
        y: 0
        z: 468
      low:
        world: BuildOff
        x: 266
        y: 0
        z: 449
  maxplayers: 10
  '2':
    server: Zedwick
    world: BuildOff
    x: 243
    y: 1
    z: 474
    high:
      world: BuildOff
      x: 250
      y: 31
      z: 468
    low:
      world: BuildOff
      x: 235
      y: 1
      z: 449
    floor:
      high:
        world: BuildOff
        x: 250
        y: 0
        z: 468
      low:
        world: BuildOff
        x: 235
        y: 0
        z: 449
  '3':
    server: Zedwick
    world: BuildOff
    x: 212
    y: 1
    z: 474
    high:
      world: BuildOff
      x: 219
      y: 31
      z: 468
    low:
      world: BuildOff
      x: 204
      y: 1
      z: 449
    floor:
      high:
        world: BuildOff
        x: 219
        y: 0
        z: 468
      low:
        world: BuildOff
        x: 204
        y: 0
        z: 449
  '4':
    server: Zedwick
    world: BuildOff
    x: 181
    y: 1
    z: 474
    high:
      world: BuildOff
      x: 188
      y: 31
      z: 468
    low:
      world: BuildOff
      x: 173
      y: 1
      z: 449
    floor:
      high:
        world: BuildOff
        x: 188
        y: 0
        z: 468
      low:
        world: BuildOff
        x: 173
        y: 0
        z: 449
  '5':
    server: Zedwick
    world: BuildOff
    x: 150
    y: 1
    z: 474
    high:
      world: BuildOff
      x: 157
      y: 31
      z: 468
    low:
      world: BuildOff
      x: 142
      y: 1
      z: 449
    floor:
      high:
        world: BuildOff
        x: 157
        y: 0
        z: 468
      low:
        world: BuildOff
        x: 142
        y: 0
        z: 449
  '6':
    server: Zedwick
    world: BuildOff
    x: 119
    y: 1
    z: 474
    high:
      world: BuildOff
      x: 126
      y: 31
      z: 468
    low:
      world: BuildOff
      x: 111
      y: 1
      z: 449
    floor:
      high:
        world: BuildOff
        x: 126
        y: 0
        z: 468
      low:
        world: BuildOff
        x: 111
        y: 0
        z: 449
  '7':
    server: Zedwick
    world: BuildOff
    x: 88
    y: 1
    z: 474
    high:
      world: BuildOff
      x: 95
      y: 31
      z: 468
    low:
      world: BuildOff
      x: 80
      y: 1
      z: 449
    floor:
      high:
        world: BuildOff
        x: 95
        y: 0
        z: 468
      low:
        world: BuildOff
        x: 80
        y: 0
        z: 449
  '8':
    server: Zedwick
    world: BuildOff
    x: 57
    y: 1
    z: 474
    high:
      world: BuildOff
      x: 64
      y: 31
      z: 468
    low:
      world: BuildOff
      x: 49
      y: 1
      z: 449
    floor:
      high:
        world: BuildOff
        x: 64
        y: 0
        z: 468
      low:
        world: BuildOff
        x: 49
        y: 0
        z: 449
  '9':
    server: Zedwick
    world: BuildOff
    x: 26
    y: 1
    z: 474
    high:
      world: BuildOff
      x: 33
      y: 31
      z: 468
    low:
      world: BuildOff
      x: 18
      y: 1
      z: 449
    floor:
      high:
        world: BuildOff
        x: 33
        y: 0
        z: 468
      low:
        world: BuildOff
        x: 18
        y: 0
        z: 449
  '10':
    server: Zedwick
    world: BuildOff
    x: -5
    y: 1
    z: 474
    high:
      world: BuildOff
      x: 2
      y: 31
      z: 468
    low:
      world: BuildOff
      x: -13
      y: 1
      z: 449
    floor:
      high:
        world: BuildOff
        x: 2
        y: 0
        z: 468
      low:
        world: BuildOff
        x: -13
        y: 0
        z: 449
  lobby:
    server: Zedwick
    world: BuildOff
    x: 118
    y: 37
    z: 561
`

**Comment by stefvanschie** [comment]
Hmm, it's strange that it's sometimes choosing the one from your arenas.yml and sometimes the one from your config.yml. However you should set the vote-timer in the arenas.yml to the correct amount of seconds. The one in the config.yml should serve as a default and will only be used if you haven't set a time in your arenas.yml.
