### ISSUE TITLE
BuildingGame breaks other plugins with sign interaction

### ISSUE THREAD

**Issue by weaves7** [stefvanschie/buildinggame#344]
## Issue

__I'm using version:__ 11.0.0
__I'm on Minecraft:__ 1.18.1
__I'm running:__ Spigot

__Seen results:__  
BuildingGame cancels PlayerInteractEvent on all signs.

__Expected results:__  
BuildingGame to only cancel PlayerInteractEvent on BuildingGame signs.

__How to reproduce:__  
Install SignShop and make a shop, you should be able to use it. Then install BuildingGame and you will no longer be able to use SignShops

__Additional info:__  
I am the current maintainer of SignShop. One of my users complained that SignShop quits working upon installing BuildingGame. SignShop ignores PlayerInteractEvents that are canceled in order to respect protection plugins. I looked at BuildingGame's code and it cancels the event anytime it is a sign being right clicked. Unfortunately other plugins also use signs during PlayerInteractEvents but cannot if they respect the event being canceled. What I propose to fix this compatibility is for BuildingGame to also return early if the first line of the sign does not match "[buildinggame]" here: https://github.com/stefvanschie/buildinggame/blob/9e71c0b7e8283f05e374c1b0866bbe8f6a3a8a3f/buildinggame/src/main/java/com/gmail/stefvanschiedev/buildinggame/events/player/signs/ClickJoinSign.java#L51 
This should/could also be added to the other BuildingGame interact listeners. Or just don't cancel the event in any of them.

**Comment by imReuthless** [comment]
I'm the original user who experienced the issue in question and contacted @weaves7. I would love to have the ability to utilize both plugins and am willing to test the changes on my server once an updated build is released. I appreciate the efforts put forth by both parties! Thank you for your dedication.

**Comment by stefvanschie** [comment]
Thank you for the bug report and apologies for the delay, I had completely forgotten about this issue. I've commited a fix for this, which will be part of the next version (11.0.1).
