### ISSUE TITLE
Some events are laggy

### ISSUE THREAD

**Issue by xion87** [stefvanschie/buildinggame#35]
i noticed some events are pretty resource eater need to be optimized, after some hours the server start to lag, i got 3 single arenas and team arenas
https://timings.spigotmc.org/?url=raxiqirayu

1.8.8 version and bb 4.0.2

**Comment by stefvanschie** [comment]
I'll see if I can make it less laggy.

**Comment by xion87** [comment]
After one day: https://timings.spigotmc.org/?url=tokimuyuco

**Comment by stefvanschie** [comment]
I will try to make it less laggy

**Comment by xion87** [comment]
my config is scoreboard-update-delay: 20

**Comment by stefvanschie** [comment]
If you have a timer in the scoreboard you probably want to keep it at 20, but if you only have placeholders that don't change often, you can probably increase it to 2-3 seconds (40-60)
