### ISSUE TITLE
[Suggestion] Add per world arenas autogenerator

### ISSUE THREAD

**Issue by Malachiel87** [stefvanschie/buildinggame#36]
you could add a simple way for create a arena by creating a void world with "room" schematics? and autogenerate a void world with these "rooms" and specific into the config or via command the size of floor and the rest, it will be more easy to create new arenas.
Example command:
/bg arena number minplayer maxplayer teammin teammax floorsize schematictouse maxhigh singleorteam

It would be awesome i think

**Comment by stefvanschie** [comment]
I'll think about it.
