### ISSUE TITLE
/bg setboundary issue

### ISSUE THREAD

**Issue by BobtheBob123456** [stefvanschie/buildinggame#389]
*You can discard this template if you're submitting a code fix/spelling mistake etc.* __Don't__ *discard this when you're submitting a bug*

## Issue

__I'm using version:__ 1.19 3
__I'm on Minecraft:__ 1.19.3
__I'm running:__ Paper

__Seen results:__  
![Screenshot_20230127-071756_Minecraft](https://user-images.githubusercontent.com/101293758/215085588-2e9d0ed5-9846-46c6-9e20-b66a80e8198e.jpg)

__Expected results:__  
I expected it to give me an item to select the boundaries for the plot.

__How to reproduce:__  
Run /bg setboundary (arena) (id)

**Comment by Daanish-Khan** [comment]
Use /bg setbounds instead.
