### ISSUE TITLE
"Wrong version"?

### ISSUE THREAD

**Issue by WolfiezRawr** [stefvanschie/buildinggame#39]
I'm running a craftbukkit 1.10.2 server and I've downloaded the 4.0.4 version of bg. When I look in my console it says "Incorrect Bukkit/Spigot version, not loading plugin". Is there any way I can fix this?

**Comment by stefvanschie** [comment]
Make sure you're using the _buildinggame-1.10.jar_.

**Comment by WolfiezRawr** [comment]
Uhm, how would I check that? xD

**Comment by stefvanschie** [comment]
Look into your plugins folder and see which version number the buildinggame file has. It should be the same as your minecraft version.

**Comment by WolfiezRawr** [comment]
Ohh no it says 1.11
Would I download an earlier version for it to be 1.10?

**Comment by stefvanschie** [comment]
You can stay on 1.10 if you like. Just go to the download page (https://dev.bukkit.org/projects/buildinggame/files/2389065) and instead of clicking Download in the upright corner scroll down a bit to "Additional files". There should be a file for minecraft version 1.10 (Make sure you download 1.10, **not** Addon 1.10).

**Comment by WolfiezRawr** [comment]
Tysm it worked!

**Comment by WolfiezRawr** [comment]
Sorry, another problem. I'm changing the subjects in the config file and then I save it but when I restart my server, the subjects go back to normal.

**Comment by stefvanschie** [comment]
Make sure your server isn't running before editing the config file.

**Comment by WolfiezRawr** [comment]
I'm super sorry for asking all of these question but the countdown to start the game stopped working.

**Comment by stefvanschie** [comment]
Does it pause when counting down or doesn't the countdown start at all?

**Comment by WolfiezRawr** [comment]
It doesn't start at all

**Comment by stefvanschie** [comment]
Did enough players join the arena? The countdown starts when the minimum required amount of players is reached.

**Comment by WolfiezRawr** [comment]
Wow I feel stupid for not knowing that haha. Thanks for all the help, really appreciate it! Everything seems to be working fine now.

**Comment by stefvanschie** [comment]
You're welcome, glad it's working.
