### ISSUE TITLE
arena placeholders

### ISSUE THREAD

**Issue by Smedve** [stefvanschie/buildinggame#398]
Hey.

Can't add arena placeholders?
%buildinggame_arena_state_<arenaname>%    >> Waiting, regenerate, ingame...
%buildinggame_arena_player_<arenaname>%  >>Show actually player numbers.
%buildinggame_arena_maxplayer_<arenaname>%  >> Show maximum player numbers.

Please add <3 
In return, I would support your work,

**Comment by stefvanschie** [comment]
These placeholders are already available in several places as `%status%`, `%players%`, and `%max_players%`. If there are places where these placeholders are not available, please let me know and then I can consider adding them.
