### ISSUE TITLE
Voting not working?

### ISSUE THREAD

**Issue by SpectrumLord** [stefvanschie/buildinggame#41]
So for some reason when I enter a game, I'm allowed to vote but my friend doesn't have the paper in his inventory so he can't vote. Also, I'm the only one who has access to the plot options. When other players click on the emerald it only shows them the book to leave the menu.

**Comment by stefvanschie** [comment]
Give them the following permissions:
_bg.subjectmenu_
_bg.buildmenu.particles_
_bg.buildmenu.floor_
_bg.buildmenu.time_
_bg.buildmenu.rain_
_bg.buildmenu.flyspeed_
_bg.buildmenu.heads_

**Comment by SpectrumLord** [comment]
Thanks man!
