### ISSUE TITLE
error while compiling

### ISSUE THREAD

**Issue by Pixelssquad** [stefvanschie/buildinggame#413]
hello, i'm a noob.
i receive this error when i try to compile /buildinggame
[ERROR] Failed to execute goal on project 1_19_0: Could not resolve dependencies for project com.gmail.stefvanschiedev:1_19_0:jar:12.4.0: The following artifacts could not be resolved: ca.bkaw:paper-nms:jar:1.19-SNAPSHOT (absent): Could not find artifact ca.bkaw:paper-nms:jar:1.19-SNAPSHOT -> [Help 1]

how to resolve pls?

**Comment by stefvanschie** [comment]
This plugin uses [paper-nms-maven-plugin](https://github.com/Alvinn8/paper-nms-maven-plugin) for NMS, which requires you to initialize the various versions used. In particular, you'll have to run the following commands:
```bash
mvn paper-nms:init -pl buildinggame/nms/1_19_0
mvn paper-nms:init -pl buildinggame/nms/1_19_1
mvn paper-nms:init -pl buildinggame/nms/1_19_2
mvn paper-nms:init -pl buildinggame/nms/1_19_3
mvn paper-nms:init -pl buildinggame/nms/1_19_4
mvn paper-nms:init -pl buildinggame/nms/1_20
```
After doing this, you should be able to build the project with `mvn clean package`. I'll update the README to include these instructions.

**Comment by stefvanschie** [comment]
Clsing this due to inactivity. If you're still having issues, please leave a comment.
