### ISSUE TITLE
no image for signs page

### ISSUE THREAD

**Issue by BabelSolea** [stefvanschie/buildinggame#42]
can ure pls refreash images or load it on github wiki page?

https://dev.bukkit.org/projects/buildinggame/pages/signs

**Comment by stefvanschie** [comment]
Should be fixed now.

**Comment by BabelSolea** [comment]
Oh! may be ure can see and some help me with that?
i writed it on another your issue page)

https://dev.bukkit.org/projects/buildinggame/issues/99

**Comment by stefvanschie** [comment]
I responded to you on the bukkit forums
