### ISSUE TITLE
Armor stand can be place outside

### ISSUE THREAD

**Issue by xion87** [stefvanschie/buildinggame#43]
Saddy, you can put armor stand outside arena ç_ç, using 1.8.8 and BG 4.0.5
![2017-03-29_22 50 11](https://cloud.githubusercontent.com/assets/3611852/24509107/cdc6fb98-1565-11e7-9952-8a0877cd4789.png)

**Comment by stefvanschie** [comment]
Will try to fix this in the next update

**Comment by stefvanschie** [comment]
Fixed this in the newest version (4.0.6)
