### ISSUE TITLE
BuildMenu is empty

### ISSUE THREAD

**Issue by iarepandemonium** [stefvanschie/buildinggame#46]
For whatever reason, the build menu is completely empty.  No errors in console.

**Comment by stefvanschie** [comment]
Make sure you've got all the correct permissions:
_bg.buildmenu.particles_
_bg.buildmenu.floor_
_bg.buildmenu.time_
_bg.buildmenu.rain_
_bg.buildmenu.flyspeed_
_bg.buildmenu.heads_
