### ISSUE TITLE
"IndexOutOfBoundsException" error during the winner phase

### ISSUE THREAD

**Issue by Phandogra** [stefvanschie/buildinggame#469]
*You can discard this template if you're submitting a code fix/spelling mistake etc.* __Don't__ *discard this when you're submitting a bug*

## Issue

__I'm using version:__ *12.7.1*  
__I'm on Minecraft:__ *1.21.1*  
__I'm running:__ *Spigot*

__Seen results:__  
*tell use what happened*
The round is aborted with an error message in the console.

__Expected results:__  
*tell use what should have happened*
The round ends correctly.

__How to reproduce:__  
*tell how this bug occured, so we can try it out ourselves*
I set up 1 arena according to the wiki and then carried out a test.
The lobby, the building and the voting worked correctly. When the winner phase starts, I get an error message on the console and the round ends.
I tried the test with the settings "Mode: Solo, Min/Max Player: 1" and "Mode: Team, Min/Max Player: 2". The result was the same.
[error.log](https://github.com/user-attachments/files/17610967/error.log)

__Additional info:__  
*more info you'd like to give us*
This is my first error report. What else do I need to provide besides the message from the console?
Thank you in advance.

**Comment by stefvanschie** [comment]
Thank you for your report, this will be fixed in version 12.8.1.
