### ISSUE TITLE
server with 2 arenas have tons of laggs with only 10-12 players.

### ISSUE THREAD

**Issue by BabelSolea** [stefvanschie/buildinggame#52]
thats very bad =(
idk what need do to ptimaze thats!

buildinggame server 10 online with only 11 plugins - laggs hard!

![image](https://cloud.githubusercontent.com/assets/23665302/24586048/273c4ad8-17a1-11e7-84ff-7b2172d918f8.png)

survival server with 40 online with 47 plugins - no laggs

**Comment by stefvanschie** [comment]
Could you do some timings of your server and show them?

**Comment by BabelSolea** [comment]
so upd info

i now fixed some options what generate errors and nw server have less laggs =)

and i add 4 arenas and averege 25 players in ne world with 5 arenas

and now i only have laggs after some matches like 15-20
when that happens - signs join stop work.
