### ISSUE TITLE
stats feature

### ISSUE THREAD

**Issue by BabelSolea** [stefvanschie/buildinggame#53]
make pls possible to off certain stats.
for example i dont need

placed blocks
broken blocks
walked

implement pls PlaceHolderAPI for game parametres:
like
in game timer
in game state

on signs need possible to show some string with arena state - waiting building ending (when players vote and win) and off

timers need to show players how long they need wait to play on arena.

need signs like:

> %arena%
> %state%
> %current_players%/%max_players%
> right click

**Comment by stefvanschie** [comment]
I'll try to add a feature to disable certain stats.
For your signs you can use these placeholders:
%arena%
%players%
%max_players%
%status&
These should allow you to change the signs like you want.

**Comment by BabelSolea** [comment]
Awesome!!!
My friend wanna make little plugin what  use MySQL info in placeholderapi,
Could ure help me a little with show part of your code about take info from MySQL?

**Comment by BabelSolea** [comment]
%status&

is not working currectly

![image](https://cloud.githubusercontent.com/assets/23665302/24696303/ad8440da-19f1-11e7-8d50-b60b45700354.png)

**Comment by BabelSolea** [comment]
![image](https://cloud.githubusercontent.com/assets/23665302/24697652/9ad28e56-19f6-11e7-80cc-4b2ba1b09640.png)
![image](https://cloud.githubusercontent.com/assets/23665302/24697662/a868a9a6-19f6-11e7-9719-0ab857f97502.png)
subject amout not working=(

**Comment by stefvanschie** [comment]
You can find most of the code including mysql here: https://github.com/stefvanschie/buildinggame/tree/master/buildinggame/1.11/src/com/gmail/stefvanschiedev/buildinggame/managers/stats

Did you stop your server before changing the config? Otherwise it'll overwrite it again.

**Comment by stefvanschie** [comment]
Added enabling/disabling specific stat types in the newest version (4.0.6)
