### ISSUE TITLE
Restart map every X matches

### ISSUE THREAD

**Issue by BabelSolea** [stefvanschie/buildinggame#55]
pls add that option to restart map/servermap after some matches to fix situations with hard laggs

**Comment by stefvanschie** [comment]
Could you please elaborate?

**Comment by BabelSolea** [comment]
![image](https://cloud.githubusercontent.com/assets/23665302/24695730/8493bcf2-19ef-11e7-8660-dda26dc55b33.png)

1. Option possible only with bungee mode ON
2. Every Arena have self counter about matches
3. In config with arenas we have string to every arena some like "autoreload_arena_after: <matches>"

so when X matches on one arena ended, players succesfully moved to BuildingGamesLobby - Arena start restart server. When thats hapens - signs about that Arena join show on string %status% what arena reloading.

so if we see what some arena have to lagg or stop working after 12 matches we can put in config autoreload: 10 - so arena will work 10 matches and reload after.

that help us create more independent servers minigame =)

**Comment by BabelSolea** [comment]
and with many arenas would be awesome to have Auto-join sign!

that sign after click move ure to arena with most near start params. like priority:

0. possible to jin arena
1. have empry slots
2. shortest time to start

so plauers will be allways have shortest time to boring waiting and allways different arenas with same mode (solo / team - need different signs)

**Comment by stefvanschie** [comment]
Oh I see what you mean, I'll try experimenting with this, don't know if it'll be ready in the next update though.

**Comment by stefvanschie** [comment]
Feature was added quite some time ago
