### ISSUE TITLE
[SOLVED] Plugin Not Working

### ISSUE THREAD

**Issue by CoolLord22** [stefvanschie/buildinggame#6]
Hey, very big issue. I did something while trying to reload the plugin (/bg reload) and now nothing works. The command appears when I press tab for the autocompletion, but when I press enter nothing works... No help menu shows up or anything. Please help!

**Comment by stefvanschie** [comment]
Are you sure the plugin loaded? When it loads, it says that it is waiting for other plugins to load. After that it should say Loading commands, Loading timers, Loading files etc.

**Comment by CoolLord22** [comment]
Yeah it says waiting for other plugins but nothing after that. I'll attach a log once I'm home. (At school atm)

**Comment by stefvanschie** [comment]
If it doesn't say that, make sure every single plugin is loaded or turn this off, config.yml > loading > load-after-plugins: false

**Comment by CoolLord22** [comment]
Alrighty. I'll let you know if it works. Thanks!

**Comment by CoolLord22** [comment]
Hey! Thanks for the help! The plugin is loading, but now there's a new issue... I can't join the arena. Here is my arenas.yml

`main-spawn:
  server: SlimeyPlayz Server
  world: TutorialHub
  x: -51
  y: 33
  z: 1080
BuildBattle:
  mode: SOLO
  '1':
    world: PaintBall
    x: 175
    y: 4
    z: -228
    floor:
      high:
        world: PaintBall
        x: 203
        y: 3
        z: -230
      low:
        world: PaintBall
        x: 177
        y: 3
        z: -256
    high:
      world: PaintBall
      x: 203
      y: 28
      z: -230
    low:
      world: PaintBall
      x: 177
      y: 4
      z: -256
  '2':
    world: PaintBall
    x: 175
    y: 4
    z: -264
    floor:
      high:
        world: PaintBall
        x: 203
        y: 3
        z: -266
      low:
        world: PaintBall
        x: 177
        y: 3
        z: -292
    high:
      world: PaintBall
      x: 203
      y: 28
      z: -266
    low:
      world: PaintBall
      x: 177
      y: 4
      z: -292
  '3':
    world: PaintBall
    x: 175
    y: 4
    z: -300
    floor:
      high:
        world: PaintBall
        x: 203
        y: 3
        z: -302
      low:
        world: PaintBall
        x: 177
        y: 3
        z: -328
    high:
      world: PaintBall
      x: 203
      y: 28
      z: -302
    low:
      world: PaintBall
      x: 177
      y: 4
      z: -328
  '4':
    world: PaintBall
    x: 175
    y: 4
    z: -336
    floor:
      high:
        world: PaintBall
        x: 203
        y: 3
        z: -338
      low:
        world: PaintBall
        x: 177
        y: 3
        z: -364
    high:
      world: PaintBall
      x: 203
      y: 28
      z: -338
    low:
      world: PaintBall
      x: 177
      y: 4
      z: -364
  '5':
    world: PaintBall
    x: 175
    y: 4
    z: -372
    high:
      world: PaintBall
      x: 203
      y: 28
      z: -374
    low:
      world: PaintBall
      x: 177
      y: 4
      z: -400
    floor:
      high:
        world: PaintBall
        x: 203
        y: 3
        z: -374
      low:
        world: PaintBall
        x: 177
        y: 3
        z: -400
  lobby:
    world: PaintBall
    x: 173
    y: 4
    z: -408
  '6':
    world: PaintBall
    x: 211
    y: 4
    z: -228
    floor:
      high:
        world: PaintBall
        x: 239
        y: 3
        z: -230
      low:
        world: PaintBall
        x: 213
        y: 3
        z: -256
    high:
      world: PaintBall
      x: 239
      y: 28
      z: -230
    low:
      world: PaintBall
      x: 213
      y: 4
      z: -256
  '7':
    world: PaintBall
    x: 211
    y: 4
    z: -264
    floor:
      high:
        world: PaintBall
        x: 239
        y: 3
        z: -266
      low:
        world: PaintBall
        x: 213
        y: 3
        z: -292
    high:
      world: PaintBall
      x: 239
      y: 28
      z: -266
    low:
      world: PaintBall
      x: 213
      y: 4
      z: -292
  '8':
    world: PaintBall
    x: 211
    y: 4
    z: -300
    floor:
      high:
        world: PaintBall
        x: 239
        y: 3
        z: -302
      low:
        world: PaintBall
        x: 213
        y: 3
        z: -328
    high:
      world: PaintBall
      x: 239
      y: 28
      z: -302
    low:
      world: PaintBall
      x: 213
      y: 4
      z: -328
  '9':
    world: PaintBall
    x: 211
    y: 4
    z: -336
    floor:
      high:
        world: PaintBall
        x: 239
        y: 3
        z: -338
      low:
        world: PaintBall
        x: 213
        y: 3
        z: -364
    high:
      world: PaintBall
      x: 239
      y: 28
      z: -338
    low:
      world: PaintBall
      x: 213
      y: 4
      z: -364
  '10':
    world: PaintBall
    x: 211
    y: 4
    z: -372
    high:
      world: PaintBall
      x: 239
      y: 28
      z: -374
    low:
      world: PaintBall
      x: 213
      y: 4
      z: -400
    floor:
      high:
        world: PaintBall
        x: 239
        y: 3
        z: -374
      low:
        world: PaintBall
        x: 213
        y: 3
        z: -400
  '11':
    world: PaintBall
    x: 247
    y: 4
    z: -228
    floor:
      high:
        world: PaintBall
        x: 275
        y: 3
        z: -230
      low:
        world: PaintBall
        x: 249
        y: 3
        z: -256
    high:
      world: PaintBall
      x: 275
      y: 28
      z: -230
    low:
      world: PaintBall
      x: 249
      y: 4
      z: -256
  '12':
    world: PaintBall
    x: 247
    y: 4
    z: -264
    floor:
      high:
        world: PaintBall
        x: 275
        y: 3
        z: -266
      low:
        world: PaintBall
        x: 249
        y: 3
        z: -292
    high:
      world: PaintBall
      x: 275
      y: 28
      z: -266
    low:
      world: PaintBall
      x: 249
      y: 4
      z: -292
  '13':
    world: PaintBall
    x: 247
    y: 4
    z: -300
    floor:
      high:
        world: PaintBall
        x: 275
        y: 3
        z: -302
      low:
        world: PaintBall
        x: 249
        y: 3
        z: -328
    high:
      world: PaintBall
      x: 275
      y: 28
      z: -302
    low:
      world: PaintBall
      x: 249
      y: 4
      z: -328
  '14':
    world: PaintBall
    x: 247
    y: 4
    z: -336
    floor:
      high:
        world: PaintBall
        x: 275
        y: 3
        z: -338
      low:
        world: PaintBall
        x: 249
        y: 3
        z: -364
    high:
      world: PaintBall
      x: 275
      y: 28
      z: -338
    low:
      world: PaintBall
      x: 249
      y: 4
      z: -364
  '15':
    world: PaintBall
    x: 247
    y: 4
    z: -372
    floor:
      high:
        world: PaintBall
        x: 275
        y: 3
        z: -374
      low:
        world: PaintBall
        x: 249
        y: 3
        z: -400
    high:
      world: PaintBall
      x: 275
      y: 28
      z: -374
    low:
      world: PaintBall
      x: 249
      y: 4
      z: -400
  minplayers: 2
`

**Comment by stefvanschie** [comment]
Does it show a message when you're trying to join?
