### ISSUE TITLE
Add a way to disable the emerald menu

### ISSUE THREAD

**Issue by zedwick** [stefvanschie/buildinggame#60]
I have removed all the permission nodes for all menus within the emerald "options" menu, but the emerald item is still shown which will bring up an empty menu, besides "Close menu".

Please add a way to disable the emerald menu either as a config, or as a permission node required to receive the options item.

**Comment by stefvanschie** [comment]
I'll add it in the next update

**Comment by zedwick** [comment]
Thank you!

**Comment by stefvanschie** [comment]
Added in the newest version (4.0.6)
