### ISSUE TITLE
Buildgame doesn't work

### ISSUE THREAD

**Issue by mrblake213** [stefvanschie/buildinggame#63]
I dowloaded Buildgame and got a .zip file with 3 jar files.

I only added "buildgame.jar" in my server files and then I restart my server and I type /bg or command anything with /bg and nothing happens and there's no responses.

**Comment by stefvanschie** [comment]
Is there a message in the console saying "BuildingGame has been enabled in x milliseconds"?

**Comment by mrblake213** [comment]
No. There isn't

**Comment by stefvanschie** [comment]
Make sure all plugins are enabled, only then the plugin will start. Or disable this in the config.yml > load > load-after-plugins: false
