### ISSUE TITLE
Cannot vote once your own plot has been voted on

### ISSUE THREAD

**Issue by zedwick** [stefvanschie/buildinggame#67]
In Building game v4.0.7, once your own plot has been voted on you are unable to vote on anyone else's plot.

If I am in plot 1, the other 2 players can vote as they wish on my plot. Voting in plot 2: I cannot vote but plot 3 player can. When voting for plot 3, plot 1 and plot 2 players cannot vote. However, once voting ends on plot 2, I auto-vote 5, and on plot 3 both I and plot 2 player will auto-vote 5.

**Comment by afronights** [comment]
same problem to me

**Comment by stefvanschie** [comment]
Verified, and will be fixed in the next version.

**Comment by stefvanschie** [comment]
Fixed in version 5.0.0.

**Comment by zedwick** [comment]
Confirmed as fixed in 5.0.0. Thanks!
