### ISSUE TITLE
Adding time placeholder to scoreboard cause derp numbers

### ISSUE THREAD

**Issue by xion87** [stefvanschie/buildinggame#7]
Hi, thank you for this amazing plugin! When i try to use " - '&6Tempo: &a%time%" placeholder into scoreboard, it showed like this, without causing any errors, using 2.20 an 1.8.8 spigot
![alt text](http://i.imgur.com/e35LdB4.png "Logo Title Text 1")

**Comment by stefvanschie** [comment]
I am aware of this bug, will be fixed in the next version.

**Comment by xion87** [comment]
Great :)

**Comment by stefvanschie** [comment]
Fixed in version 2.2.1
