### ISSUE TITLE
Signs error

### ISSUE THREAD

**Issue by MrWay** [stefvanschie/buildinggame#70]
Hi,
after i place a sign (anyhow), it left just blank and in console it shows this error: http://prntscr.com/fnh1ec

Thank you.

**Comment by MrWay** [comment]
http://prntscr.com/fnh35z

**Comment by stefvanschie** [comment]
It seems like the server forgot the name of a player that the plugin needs. I'll add a fix for that, but I can't magically discover the name of the player if the server forgot it, so it'd still show an incorrect name.

If you happen to know which player should be displayed on the stat sign you can ask him/her to join the server again. Then the server should remember his/her name again and it'd be fixed once the stat signs refresh again.

**Comment by stefvanschie** [comment]
Fixed in version 5.0.0.
