### ISSUE TITLE
[BuildingGame] Incorrect Bukkit/Spigot version, not loading plugin.

### ISSUE THREAD

**Issue by afronights** [stefvanschie/buildinggame#71]
Problem with the new version (BuildingGame 5.0.0)

[BuildingGame] Incorrect Bukkit/Spigot version, not loading plugin.

**Comment by stefvanschie** [comment]
The new version requires Spigot (or Bukkit) 1.12, instead of 1.11.2, so make sure you're using that one.

**Comment by afronights** [comment]
Ok thank u !!!
