### ISSUE TITLE
Unable to set bounds in 1.12

### ISSUE THREAD

**Issue by o1230sponge** [stefvanschie/buildinggame#72]
Every time I type the setbounds command, it just gives me this error
![2017-07-20_13 26 06](https://user-images.githubusercontent.com/15003412/28430598-19e8cad8-6d4f-11e7-92a6-cd54f577cc3b.png)

Everything else has worked with little issue so far

**Comment by stefvanschie** [comment]
Have you already created the plot you want to set the boundary for? The plot needs to be created before you can set the bound.

**Comment by o1230sponge** [comment]
I have created the plot. From tutorials I've watched, I should receive a wand, yes?

**Comment by stefvanschie** [comment]
Yes, but you'll only be given a wand when the command is accepted, so when it says "That's not a valid plot", it won't give you one.
/bg setspawn <arena> will create a new plot and shows you the plot id. Then you can use /bg setbounds <arena> <id> with that same id to create a boundary. Are you sure that's what you did?

**Comment by o1230sponge** [comment]
Ah, I understand now. Thank you for your assistance!
