### ISSUE TITLE
New round starts immediately after displaying winning plot

### ISSUE THREAD

**Issue by zedwick** [stefvanschie/buildinggame#73]
A new round started immediately after displaying the winning plot without sending players back to lobby. Boss bar did not show with time in this new round.

It did run fine after the first round on the server, we were sent back to the lobby to wait for a new round to begin. The new round started after the correct amount of time in the lobby, but after this second round began an infinite loop of rounds without a lobby break in between.

Running BuildingGame 5.0.0
Paper 1.12
Players: 3

**Comment by stefvanschie** [comment]
Verified, will fix it in the next update.

**Comment by stefvanschie** [comment]
Fixed in version 5.0.1

**Comment by zedwick** [comment]
Confirmed as fixed in 5.0.1, thanks.
