### ISSUE TITLE
Firework effect error

### ISSUE THREAD

**Issue by afronights** [stefvanschie/buildinggame#74]
At the end of the game the server kicked me out: 
ERROR]: java.lang.IllegalStateException: Cannot make FireworkEffect without any color.

Thank you for the patience.

**Comment by stefvanschie** [comment]
Yeah, they changed fireworks again in 1.12 for some weird reason. If you remove the win-commands section int he config.yml (I assume that's where you have the firework commands are located)it'll regenerate them correctly for them if I'm not mistaken.

**Comment by afronights** [comment]
I tried to erase the entire config.yml but it's the same problem.

**Comment by stefvanschie** [comment]
Could you show the firework commands?

**Comment by afronights** [comment]
- '%console% execute %winner% ~1 ~ ~-4 summon fireworks_rocket ~ ~5 ~ {FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:0,Colors:[14263784,581228,995542,3255052,13888116,4175055],FadeColors:[8848460]}]}}}}'
- '%console% execute %winner% ~-2 ~ ~3 summon fireworks_rocket ~ ~5 ~ {FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:2,Colors:[14495340,12909992,8969028,7924605],FadeColors:[10438567,12267580,2724499,9942861]}]}}}}'
- '%console% execute %winner% ~-4 ~ ~1 summon fireworks_rocket ~ ~5 ~ {FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:0,Colors:[2540754],FadeColors:[14655338,2417053,631931,4555299,15572482,3482736,693669]}]}}}}'

**Comment by stefvanschie** [comment]
Huh, apparently I didn't change them in the config. Oh well, here are the fixed commands, these should be compatible with 1.12:

- '%console% execute %winner% ~1 ~ ~-4 summon fireworks_rocket ~ ~5 ~ {FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:0,Colors:[I;14263784,581228,995542,3255052,13888116,4175055],FadeColors:[I;8848460]}]}}}}'

- '%console% execute %winner% ~-2 ~ ~3 summon fireworks_rocket ~ ~5 ~ {FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:2,Colors:[I;14495340,12909992,8969028,7924605],FadeColors:[I;10438567,12267580,2724499,9942861]}]}}}}'

- '%console% execute %winner% ~-4 ~ ~1 summon fireworks_rocket ~ ~5 ~ {FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:0,Colors:[I;2540754],FadeColors:[I;14655338,2417053,631931,4555299,15572482,3482736,693669]}]}}}}'

**Comment by afronights** [comment]
Ok thank u now it works !!!
Two problem now:
1) At the voting time the player sometimes can be spawned inside a wall !!!
2) After the first game if you try to rejoin, the game restart with an infinite loop.

**Comment by stefvanschie** [comment]
1. I'll see if I can fix this
2. Will be fixed in the next update (someone else reported that too :) )

**Comment by afronights** [comment]
Ok thank u.

How long will it take for the next update ? :-)

**Comment by stefvanschie** [comment]
Depends, I've got most of the bugs fixed (with the exception for this one which I'll be working on the upcoming days) so as long as no one else reports a bug the update will probably come out in a few days. But if others find more bugs (and report them) it may take a bit longer.

**Comment by stefvanschie** [comment]
Fixed in version 5.0.1

**Comment by afronights** [comment]
Ok Thank you version 5.0.1 works !
