### ISSUE TITLE
Hint for players spawn

### ISSUE THREAD

**Issue by afronights** [stefvanschie/buildinggame#75]
I found that the new player spawn, at voting time, is at upper corner of the plot area, with X and Z at the origin points of the plot.

I would advise you that  maybe with Y-(Y/2) ( height / 2 ), X+(1/4*X) and Z+(1/4*Z) of spawn coordinates, with a Yaw angle (face angle) of 45° it would be optimal.

Thanks for the involvement !!!! :-)

**Comment by stefvanschie** [comment]
When spawning the player the plugin looks for a safe spot to teleport the players to (so they don't get stuck in blocks). When searching it starts at the upper corner, so if that's a safe spot it will teleport them to there. If I were to change the position to the one you suggested, it may be that players get stuck in blocks again which would be even more annoying.

**Comment by afronights** [comment]
Ok that is correct.

If you want a cool point of view, you should change the spawn coordinates and verify first if there is a existing block.

With my map the plots has a high height and then when player spawns, the point of view is too far and the head is not turned in the right way.

**Comment by stefvanschie** [comment]
Well I could make the head face the center of the plot, that way it should look a bit better.

**Comment by afronights** [comment]
ok it would be perfect !

**Comment by stefvanschie** [comment]
Changed in version 5.0.2.
