### ISSUE TITLE
Stats scoreboard errors

### ISSUE THREAD

**Issue by afronights** [stefvanschie/buildinggame#78]
There is error in displaying data in stats scoreboard in the lobby.

And then at the end of the match, with two player, with the money assignment.

**Comment by stefvanschie** [comment]
Could you elaborate on the errors you're getting?

**Comment by Zoiter7** [comment]
The issue is in your scoreboard seems is displaying the stats of other player.
But if you alone in the server or lobby, the stats is displaying correctly.

**Comment by afronights** [comment]
After the first game when return to spawn, the scoreboard disappear.
If I disconnect and reconnect the scoreboard reappear with all 0 values.
The money assignment at first time assign right money but after assign at first 40 and to the second 10. And sometimes at the first 20 and to second 20.

**Comment by stefvanschie** [comment]
There is a permission node that doubles the amount of money you get (_bg.rewards.money.double_). Looking at the values you posted that's probably what's happening.

I've verified the issue with the main scoreboard, I'm working on it.

**Comment by afronights** [comment]
I'm tried 5.03, but scoreboard, after the game, disappears.
If i change world and come back it reappears.

**Comment by stefvanschie** [comment]
Issues have been fixed in version 5.0.4
