### ISSUE TITLE
BossBar

### ISSUE THREAD

**Issue by Radeux** [stefvanschie/buildinggame#80]
Pls Help Me My Error
 https://i.hizliresim.com/jWaODj.png

**Comment by stefvanschie** [comment]
Link returns an HTTP 404 Error on Google Chrome and Internet Explorer and an image error on Mozilla Firefox

**Comment by Radeux** [comment]
Sorry 
https://ibb.co/n4zVsF

**Comment by stefvanschie** [comment]
Try running with the latest version (5.0.2).

**Comment by Radeux** [comment]
My Second Error with (5.0.2)
https://ibb.co/fESxNF

**Comment by stefvanschie** [comment]
You need to have [Socket4MC](https://www.spigotmc.org/resources/api-socket4mc.15938/) installed to be able to run the BungeeCord version.
