### ISSUE TITLE
No plot URGENT!

### ISSUE THREAD

**Issue by DolphinGamerYT** [stefvanschie/buildinggame#83]
Hi,
In your plugin for 1.8, I set bounds and says its not a plot.

**Comment by stefvanschie** [comment]
I don't support previous builds as the issue you mentioned may have already been fixed.

**Comment by DolphinGamerYT** [comment]
Omg pls update 1.8.8

**Comment by stefvanschie** [comment]
I've dropped support for 1.8 already 3 months ago, and I'm not planning on adding it back.
