### ISSUE TITLE
vote tiime don't work

### ISSUE THREAD

**Issue by DariusKing** [stefvanschie/buildinggame#91]
Votation time don't work

__I'm using version:__ *Building Game 5.3.2*  
__I'm on Minecraft:__ *1.12-optifine*  
__I'm running:__ *Spigot 1.8-1.12 server*

__Seen results:__  
*when the build time finish and start the vote time, this doesn't work, the game has stopped on the votation of the first build, and don't change to the next*

__Expected results:__  
*it's the first time, when i configure this plugin this is for a new minecraft server, i was do the configuracion like SoulStriker video, but i have problems, when i edit the config.yml and the message.yml*

__How to reproduce:__  
*i don't know, can you recommend me a solution or its necessary probe on a clean installation*

__Additional info:__  
*the vote time was set on 15 with /bg setvottimer (arena) 15*

**Comment by stefvanschie** [comment]
Could you show me your arenas.yml and config.yml?
