### ISSUE TITLE
Set your commas

### ISSUE THREAD

**Issue by draebersnegl** [stefvanschie/buildinggame#96]
https://github.com/stefvanschie/buildinggame/blob/7865760d04b088d9c367154030a28fd3a31480ea/buildinggame/src/com/gmail/stefvanschiedev/buildinggame/managers/stats/MySQLDatabase.java#L68

**Comment by stefvanschie** [comment]
Thanks, I'll fix this bug in the next update.

**Comment by stefvanschie** [comment]
Fixed in latest commit, version 5.5.0 will include this fix.
